//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Date
    {
        public int DateId { get; set; }
        public Nullable<System.DateTime> Dt { get; set; }
        public Nullable<System.DateTimeOffset> dtO { get; set; }
    }
}
