//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPerson_Address
    {
        public int Person_AddressId { get; set; }
        public int PersonId { get; set; }
        public int AddressId { get; set; }
    
        public virtual teAddress teAddress { get; set; }
        public virtual tePerson tePerson { get; set; }
    }
}
