//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericTesting
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TesterEntities : DbContext
    {
        public TesterEntities()
            : base("name=TesterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbPerson_Address> tbPerson_Address { get; set; }
        public virtual DbSet<teAddress> teAddresses { get; set; }
        public virtual DbSet<teOrder> teOrders { get; set; }
        public virtual DbSet<tePerson> tePersons { get; set; }
        public virtual DbSet<Date> Dates { get; set; }
    }
}
