//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCSharpTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class teSku
    {
        public int SkuId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Description { get; set; }
    
        public virtual teOrder teOrder { get; set; }
    }
}
