//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityTesting
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TesterEntities : DbContext
    {
        public TesterEntities()
            : base("name=TesterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<teOrder> teOrder { get; set; }
        public virtual DbSet<tePerson> tePerson { get; set; }
    
        public virtual ObjectResult<pDynamicGroupTest_Result> pDynamicGroupTest(string xml)
        {
            var xmlParameter = xml != null ?
                new ObjectParameter("Xml", xml) :
                new ObjectParameter("Xml", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pDynamicGroupTest_Result>("pDynamicGroupTest", xmlParameter);
        }
    }
}
